# This config file is used by ros2_control
/follower:
  controller_manager:
    ros__parameters:
      update_rate: 25  # Hz

      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      gripper_controller:
        type: position_controllers/GripperActionController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  arm_controller:
    ros__parameters:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow_flex
        - wrist_flex
        - wrist_roll
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        
  gripper_controller:
    ros__parameters:
      type: position_controllers/GripperActionController
      joint: gripper

/leader:
  controller_manager:
    ros__parameters:
      update_rate: 25  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  joint_state_broadcaster:
    ros__parameters:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow_flex
        - wrist_flex
        - wrist_roll
        - gripper

      interfaces:
        - position
