arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  # position_only_ik: True
  # solve_type: Distance

# TODO: add bio_ik
# arm:
#   kinematics_solver: bio_ik/BioIKKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.02
#   kinematics_solver_attempts: 1.0

  # optional bio_ik configuration parameters
  #  center_joints_weight: 1.0
  #  minimal_displacement_weight: 1.0
  #  avoid_joint_limits_weight: 1.0